name: First workflow
on: workflow_dispatch
jobs:
  First-jobs
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello World"
    - name: Print good bye
      run: echo "Bye World"
